services:
  postgres:
    image: postgres:12
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_SM
    volumes:
      - .:/app
      - postgres-data-dojo:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres-network

  pgadmin:
    image: elestio/pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    user: root
    volumes:
      - .:/home
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data-dojo:
